name: Package

on:
  push:
    tags:
      - "*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows_package:
    runs-on: windows-2019
    if: (github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'package'))
    strategy:
      matrix:
        arch: [x64]
        python: ["3.7","3.8","3.9","3.10"]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python}}
          architecture: ${{ matrix.arch }}

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: '%LOCALAPPDATA%\pip\Cache'
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('tox.ini', 'setup.py', 'requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Prepare pip
        run: python -m pip install --upgrade pip

      - name: Install Deluge
        run: |
          python setup.py bdist_egg

      - uses: actions/upload-artifact@v3
        with:
          name: SeedHate-py${{ matrix.python }}
          path: dist/*.egg

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: latest
          tag_name: latest
          body: ${{ steps.date.outputs.date }}
          files: "dist/*.egg"
